name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "Updating system"
            sudo yum update -y

            echo "Installing Apache"
            sudo yum install httpd -y

            echo "Starting Apache"
            sudo systemctl enable httpd
            sudo systemctl start httpd

            echo "Installing Git"
            sudo yum install git -y

            echo "Deploying application"
            sudo mkdir -p /var/www/app
            cd /var/www/app
            echo "Setting permissions"
